### ISSUE TITLE
Error using deno bundle with React: Type 'C' does not satisfy the constraint 'ElementType<any>'

### ISSUE THREAD

**Issue by quaos** [postui/esm.sh#1]
I'm trying to use `deno bundle` with esm React v17.0.1, but got this error:

```shell
$ deno bundle --config tsconfig.json src/client.tsx public/assets/js/client.js
Bundle file:///.../deno-react-minimal-frontend/src/client.tsx
Check file:///.../deno-react-minimal-frontend/src/client.tsx
Unsupported compiler options in "/.../deno-react-minimal-frontend/tsconfig.json".
  The following options were ignored:
    allowUmdGlobalAccess, disableSizeLimit, esModuleInterop, module, moduleResolution, noEmit, preserveConstEnums, resolveJsonModule, skipLibCheck, sourceMap, target
error: TS2344 [ERROR]: Type 'C' does not satisfy the constraint 'ElementType<any>'.
  Type 'string | number | ForwardRefExoticComponent<any> | (new (props: any) => Component<any, {}, any>) | ((props: any, context?: any) => ReactElement<any, string | ((props: any) => ReactElement<...> | null) | (new (props: any) => Component<...>)> | null)' is not assignable to type 'ElementType<any>'.
    Type 'number' is not assignable to type 'ElementType<any>'.
      Type 'C' is not assignable to type 'FunctionComponent<any>'.
        Type 'string | number | ForwardRefExoticComponent<any> | (new (props: any) => Component<any, {}, any>) | ((props: any, context?: any) => ReactElement<any, string | ((props: any) => ReactElement<...> | null) | (new (props: any) => Component<...>)> | null)' is not assignable to type 'FunctionComponent<any>'.
          Type 'string' is not assignable to type 'FunctionComponent<any>'.
        "ref" extends keyof ComponentPropsWithRef<C>
                                                  ^
    at https://esm.sh/@types/react@16.9.54/index.d.ts:120:51

TS2344 [ERROR]: Type 'C' does not satisfy the constraint 'ElementType<any>'.
  Type 'C' is not assignable to type 'FunctionComponent<any>'.
            ? NonNullable<ComponentPropsWithRef<C>["ref"]> extends Ref<
                                                ^
    at https://esm.sh/@types/react@16.9.54/index.d.ts:121:49

Found 2 errors.
```

Here is my import/export part of code:
```typescript
export { default as React } from "https://esm.sh/react@17.0.1";

export { default as ReactDOM } from "https://esm.sh/react-dom@17.0.1";
```

My environment:
Deno v1.5.2
OS: macOS Mojave 10.14.6

**Comment by ije** [comment]
i will figure it out, thanks!

you can try to disable the types check temporarily:
```javacript
export { default as React } from "https://esm.sh/react@17.0.1?no-check";
```

**Comment by ije** [comment]
@quaos `deno bundle src/client.tsx public/assets/js/client.js` without `--config` seems works fine in my case:

<img width="699" alt="Screenshot 2020-11-13 at 20 57 07" src="https://user-images.githubusercontent.com/2883484/99074489-cd344400-25f2-11eb-9aa8-bb4c3a57c97c.png">

can you please post the `tsconfig.json`?

**Comment by quaos** [comment]
@ije Here:
***tsconfig.json***
```json
{
  "compilerOptions": {
    "isolatedModules": false,
    "allowJs": false,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "alwaysStrict": true,
    "checkJs": false,
    "disableSizeLimit": false,
    "jsx": "react",
    "jsxFactory": "React.createElement",
    "lib": ["DOM", "ESNext"],
    "noFallthroughCasesInSwitch": false,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitUseStrict": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "removeComments": false,
    "strict": true,
    "strictBindCallApply": true,
    "strictFunctionTypes": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": true,
    "suppressExcessPropertyErrors": false,
    "suppressImplicitAnyIndexErrors": false
  },
  "deno": true
}
```

In my case, omitting `--config` still yields the same errors, with more errors about jsx added in:
```shell
TS17004 [ERROR]: Cannot use JSX unless the '--jsx' flag is provided.
    <App />,
```

**Comment by quaos** [comment]
> i will figure it out, thanks!
> 
> you can try to disable the types check temporarily:
> 
> ```js
> export { default as React } from "https://esm.sh/react@17.0.1?no-check";
> export { default as ReactDOM } from "https://esm.sh/react-dom@17.0.1?no-check";
> ```

Thanks, the bundle succeeded with `?no-check` !
However, the result `client.js` still has error in browser:
```
Uncaught ReferenceError: __react is not defined
    at require (client.js:370)
```

[client.js.zip](https://github.com/postui/esm.sh/files/5540220/client.js.zip)

**Comment by ije** [comment]
i see, thanks.
i guess this is a bug in deno bundler.

**Comment by ije** [comment]
FYI please check https://github.com/denoland/deno/issues/8344

**Comment by ije** [comment]
@quaos  to get react render details error message, you can use esm.sh's `dev` mode:

```javascript
import _React from 'https://esm.sh/[react,react-dom]/react?dev'
import _ReactDOM from 'https://esm.sh/[react,react-dom]/react-dom?dev'
export const React = _React
export const ReactDOM = _ReactDOM
```

**Comment by quaos** [comment]
@ije Somewhat after using development mode, the error is gone and React components loaded successfully now.
```typescript
import _React from 'https://esm.sh/[react,react-dom]/react?dev&no-check';
import _ReactDOM from 'https://esm.sh/[react,react-dom]/react-dom?dev&no-check';
```

**Comment by ije** [comment]
cool, what deno version you are using? i don't need `no-check` flag in deno `1.5.2`

**Comment by ije** [comment]
consider use [Aleph.js](https://alephjs.org) ?

**Comment by quaos** [comment]
@ije I also uses 1.5.2, but do not work without `no-check`
```shell
>deno --version
deno 1.5.2 (71d7482, release, x86_64-pc-windows-msvc)
v8 8.7.220.3
typescript 4.0.5
```

However, this is the repo I've been working on:
[deno-react-minimal-frontend](https://github.com/quaos/deno-react-minimal-frontend)

**Comment by ije** [comment]
cool!

**Comment by quaos** [comment]
@ije So I suppose you can close this issue now 😎
