### ISSUE TITLE
v45 resolves Node.js `path` incorrectly

### ISSUE THREAD

**Issue by talentlessguy** [postui/esm.sh#103]
In v45, modules that use node.js `path`, no longer work properly:

```ts
import { contentDisposition } from 'https://esm.sh/@tinyhttp/content-disposition@2.0.0'
```

results in this:

```
error: Uncaught SyntaxError: The requested module '/v45/path-browserify@1.0.1/deno/path-browserify.js' does not provide an export named 'basename'
    at <anonymous> (https://cdn.esm.sh/v45/@tinyhttp/content-disposition@2.0.0/deno/content-disposition.js:2:66)
```

trying to import from `v44`:

```ts
import { contentDisposition } from 'https://cdn.esm.sh/v44/@tinyhttp/content-disposition@2.0.0/deno/content-disposition.js'
```

yields this:

```
error: Uncaught SyntaxError: The requested module '/v45/path-browserify@1.0.1/deno/path-browserify.js' does not provide an export named 'basename'
    at <anonymous> (https://cdn.esm.sh/v44/@tinyhttp/content-disposition@2.0.0/deno/content-disposition.js:2:66)
```

here's the source code for a module: https://github.com/tinyhttp/tinyhttp/blob/master/packages/content-disposition/src/index.ts

**Comment by ije** [comment]
@talentlessguy thanks, i will look into it!

**Comment by ije** [comment]
@talentless fixed, v46 should work fine, pls clean cache and try again, thanks
