### ISSUE TITLE
Bundle doesn't seem to have been generated - 404

### ISSUE THREAD

**Issue by FallingSnow** [postui/esm.sh#13]
```js
INFO Download https://esm.sh/react • https://esm.sh/[react,react-hook-form,@fluentui/react,react-flow-renderer,swr]/react?target=es2018&dev
INFO Download https://cdn.esm.sh/bundle-ojv7uwoviwslf342bemex5fq7b4wvqk3.js 
error: Uncaught (in promise) Error: Download https://cdn.esm.sh/bundle-ojv7uwoviwslf342bemex5fq7b4wvqk3.js: Download https://cdn.esm.sh/bundle-ojv7uwoviwslf342bemex5fq7b4wvqk3.js: 404 - Not Found
                    throw new Error(`Download ${url}: ${err.message}`)
```

import_map.json
```json
{
    "imports": {
        "https://esm.sh/": "https://esm.sh/[react,react-hook-form,@fluentui/react,react-flow-renderer,swr]/"
    }
}
```

**Comment by FallingSnow** [comment]
Error when visiting `https://cdn.esm.sh/bundle-ojv7uwoviwslf342bemex5fq7b4wvqk3.js`:
```js
/* esm.sh - error */
throw new Error("[esm.sh] " + "npm: package 'bundle-ojv7uwoviwslf342bemex5fq7b4wvqk3.js' not found");
export default null;
``

**Comment by ije** [comment]
please try `deno --reload run [...]`, i will fix this (new server deployment will clean up the old builds)

**Comment by FallingSnow** [comment]
I'm using Aleph. What command would I run for that? I already tried

```js
$ rm -rf .aleph
$ aleph dev
INFO Download https://esm.sh/graphql • https://esm.sh/[react,react-hook-form,@fluentui/react,react-flow-renderer,swr,graphql]/graphql?target=es2018&dev
INFO Download https://cdn.esm.sh/bundle-afim5jp55sr57xkzkzahvfk7mmkygh6l.js 
error: Uncaught (in promise) Error: Download https://cdn.esm.sh/bundle-afim5jp55sr57xkzkzahvfk7mmkygh6l.js: Download https://cdn.esm.sh/bundle-afim5jp55sr57xkzkzahvfk7mmkygh6l.js: 404 - Not Found
```

Made a slight change to `import_map.json` to work around the graphql issue (#14) right now. (Note the addition of graphql)
```json
{
    "imports": {
        "https://esm.sh/": "https://esm.sh/[react,react-hook-form,@fluentui/react,react-flow-renderer,swr,graphql]/"
    }
}
```

**Comment by ije** [comment]
```
aleph dev --reload
```

**Comment by ije** [comment]
i know what happened, i will fix it ASAP, thanks! please use package link instead of the bundle link, aleph **v0.3** will bundle the code in production mode.

**Comment by ije** [comment]
should work now:
https://esm.sh/[react,react-dom,swr]/react

**Comment by FallingSnow** [comment]
Not sure if I'm using this right.
```js
INFO Download https://esm.sh/tailwindcss/dist/tailwind.min.css • https://esm.sh/[react,react-hook-form,react-flow-renderer,swr]/tailwindcss/dist/tailwind.min.css?target=es2018&dev
error: Uncaught (in promise) Error: Download https://esm.sh/tailwindcss/dist/tailwind.min.css: Download https://esm.sh/tailwindcss/dist/tailwind.min.css: 500 - Internal Server Error
```
```js
/* esm.sh - error */
throw new Error("[esm.sh] " + "npm: package '[react,react-hook-form,react-flow-renderer,swr]' not found");
export default null;
```

**Comment by shadowtime2000** [comment]
@FallingSnow CAn you share the imports?

**Comment by FallingSnow** [comment]
import_map.json
```json
{
    "imports": {
        "https://esm.sh/": "https://esm.sh/[react,react-hook-form,react-flow-renderer,swr]/"
    }
}
```

**Comment by shadowtime2000** [comment]
@FallingSnow You have to change that to `[react,react-hook-form,react-flow-renderer,swc,tailwindcss]` because the import to tailwind is being prefixed with that bundle which makes it invalid cuz tailwind isn't included in it.

**Comment by FallingSnow** [comment]
Is there a way I could make a bundle for react related modules and no bundles for the others?

**Comment by shadowtime2000** [comment]
@FallingSnow 

```json
{
    "imports": {
        "react": "https://esm.sh/[react,react-hook-form,react-flow-renderer,swr]/"
    }
}
```
Then you just do
```js
import "react/swr";
```
or whatever you want.

**Comment by FallingSnow** [comment]
Hmmm, now I'm running into this:
```js
$ aleph dev -L debug
DEBUG compile '/app.tsx' in 66ms
error: Uncaught (in promise) NotFound: No such file or directory (os error 2)
    at processResponse (deno:core/core.js:223:11)
    at Object.jsonOpAsync (deno:core/core.js:240:12)
    at async open (deno:runtime/js/30_files.js:44:17)
    at async Object.readFile (deno:runtime/js/40_read_file.js:15:18)
    at async Project._compile (project.ts:1019:29)
    at async Project._compile (project.ts:1169:28)
    at async Project._init (project.ts:655:21)
    at async project.ts:106:13
    at async start (server.ts:12:5)
```

Not sure what's causing it.

**Comment by FallingSnow** [comment]
I modified the aleph source to see which file it was trying to read in project.ts. @shadowtime2000 Am I doing something wrong or is the module resolution not working as expected?

```js
$ aleph dev -L debug
{ filepath: "/home/ayrton/Coding/node/mmes/server/app.tsx" }
DEBUG compile '/app.tsx' in 65ms
{ filepath: "/home/ayrton/Coding/node/mmes/server/style/index.less" }
{ filepath: "/home/ayrton/Coding/node/mmes/server/react/react" }
error: Uncaught (in promise) NotFound: No such file or directory (os error 2)
    at processResponse (deno:core/core.js:223:11)
    at Object.jsonOpAsync (deno:core/core.js:240:12)
    at async open (deno:runtime/js/30_files.js:44:17)
    at async Object.readFile (deno:runtime/js/40_read_file.js:15:18)
    at async Project._compile (project.ts:1023:29)
    at async Project._compile (project.ts:1173:28)
    at async Project._init (project.ts:658:21)
    at async project.ts:106:13
    at async start (server.ts:12:5)
```

app.tsx
```ts
import React, { ComponentType } from "react/react";
```

import_map.json
```json
{
    "imports": {
        "react": "https://esm.sh/[react,react-hook-form,react-flow-renderer,swr,@fluentui/react,@uifabric/icons]/"
    }
}
```

**Comment by FallingSnow** [comment]
Looks like it was failing https://github.com/alephjs/aleph.js/blob/0456c9da64ba09967a1b376358c93e8991bdff97/project.ts#L1022 is remote test.

**Comment by ije** [comment]
i think using esm.sh's bundle mode in alephjs is not a good idea since the alephjs will handle the react import URL. and **0.3** will bundle the app in production mode.

**Comment by FallingSnow** [comment]
Oh ok, I forgot you already said this and just kept charging forward, oops.

I did get it pretty close to working, it actually imports now.
```

```
