### ISSUE TITLE
Strange esm.sh error

### ISSUE THREAD

**Issue by RoXuS** [postui/esm.sh#34]
Hey!

For some reason we can't start our project (this project is inside a docker and it was ok before last releases of esm.sh).

The error is the following:

```
Check https://deno.land/x/aleph@v0.2.28/cli/start.ts
error: Uncaught (in promise) TypeError: AssertionError: "data" is unexpectedly null for "https://esm.sh/v25/_node.ns.d.ts".
    at assert (deno:cli/tsc/99_main_compiler.js:59:13)
    at Object.getSourceFile (deno:cli/tsc/99_main_compiler.js:268:7)
    at findSourceFileWorker (deno:cli/tsc/00_typescript.js:106861:29)
    at findSourceFile (deno:cli/tsc/00_typescript.js:106771:26)
    at deno:cli/tsc/00_typescript.js:106728:85
    at getSourceFileFromReferenceWorker (deno:cli/tsc/00_typescript.js:106695:34)
    at processSourceFile (deno:cli/tsc/00_typescript.js:106728:13)
    at deno:cli/tsc/00_typescript.js:107014:17
    at Object.forEach (deno:cli/tsc/00_typescript.js:382:30)
    at processReferencedFiles (deno:cli/tsc/00_typescript.js:107012:16)
    ```

**Comment by ije** [comment]
@RoXuS fixed
