### ISSUE TITLE
[Error]: Import or export declaration

### ISSUE THREAD

**Issue by timreichen** [postui/esm.sh#35]
I came across these errors while trying to download `html-minifier`. Is this intentional or can it be fixed?

```sh
Download http://esm.sh/html-minifier
Download https://cdn.esm.sh/v27/html-minifier@4.0.0/deno/html-minifier.js
Download https://cdn.esm.sh/v27/@types/html-minifier@4.0.0/index.d.ts
Download https://cdn.esm.sh/v27/stream-http@3.1.1/deno/stream-http.js
Download https://cdn.esm.sh/v27/url@0.11.0/deno/url.js
Download https://cdn.esm.sh/v27/https-browserify@1.0.0/deno/https-browserify.js
Download https://cdn.esm.sh/v27/_node_process.js
Download https://cdn.esm.sh/v27/path-browserify@1.0.1/deno/path-browserify.js
Download https://cdn.esm.sh/v27/os-browserify@0.3.0/deno/browser.js
Download https://cdn.esm.sh/v27/_node_buffer.js
Download https://deno.land/std@0.90.0/node/fs.ts
Download https://cdn.esm.sh/v27/@types/relateurl@0.2.28/index.d.ts
Download https://cdn.esm.sh/v27/@types/uglify-js@3.13.0/index.d.ts
Download https://cdn.esm.sh/v27/@types/clean-css@4.2.3/index.d.ts
Download https://cdn.esm.sh/v27/buffer@6.0.3/deno/buffer.js
Download https://cdn.esm.sh/v27/events@3.3.0/deno/events.js
Download https://cdn.esm.sh/v27/util@0.12.3/deno/util.js
Download https://cdn.esm.sh/v27/punycode@2.1.1/deno/punycode.js
Download https://cdn.esm.sh/v27/querystring-es3@0.2.1/deno/querystring-es3.js
Download https://cdn.esm.sh/v27/@types/node@14.14.35/http.d.ts
Download https://cdn.esm.sh/v27/@types/node@14.14.35/https.d.ts
Download https://esm.sh/v27/_node.ns.d.ts
Download https://cdn.esm.sh/v27/source-map@0.6.1/source-map.d.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_chown.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_mkdir.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_constants.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_mkdtemp.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_realpath.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_rmdir.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_access.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_appendFile.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_unlink.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_readdir.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_watch.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_open.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_stat.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_lstat.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_truncate.ts
Download https://deno.land/std@0.90.0/node/_fs/promises/mod.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_rename.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_close.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_writeFile.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_chmod.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_readFile.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_readlink.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_exists.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_copy.ts
Download https://deno.land/std@0.90.0/node/path.ts
Download https://deno.land/std@0.90.0/node/_utils.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_common.ts
Download https://deno.land/std@0.90.0/node/buffer.ts
Download https://cdn.esm.sh/v27/node:stream
Download https://cdn.esm.sh/v27/node:url
Download https://cdn.esm.sh/v27/node:net
Download https://deno.land/std@0.90.0/node/_errors.ts
Download https://deno.land/std@0.90.0/node/events.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_dirent.ts
Download https://deno.land/std@0.90.0/node/_fs/promises/_fs_readFile.ts
Download https://deno.land/std@0.90.0/node/_fs/promises/_fs_writeFile.ts
Download https://deno.land/std@0.90.0/fs/mod.ts
Download https://cdn.esm.sh/v27/node:tls
Download https://cdn.esm.sh/v27/node:http
Download https://deno.land/std@0.90.0/async/mod.ts
Download https://deno.land/std@0.90.0/testing/asserts.ts
Download https://deno.land/std@0.90.0/path/mod.ts
Download https://deno.land/std@0.90.0/encoding/base64.ts
Download https://deno.land/std@0.90.0/encoding/hex.ts
Download https://deno.land/std@0.90.0/_util/assert.ts
Download https://deno.land/std@0.90.0/node/util.ts
Download https://deno.land/std@0.90.0/fs/walk.ts
Download https://deno.land/std@0.90.0/fs/eol.ts
Download https://deno.land/std@0.90.0/fs/exists.ts
Download https://deno.land/std@0.90.0/fs/ensure_dir.ts
Download https://deno.land/std@0.90.0/fs/move.ts
Download https://deno.land/std@0.90.0/fs/copy.ts
Download https://deno.land/std@0.90.0/fs/expand_glob.ts
Download https://deno.land/std@0.90.0/fs/ensure_link.ts
Download https://deno.land/std@0.90.0/fs/ensure_symlink.ts
Download https://deno.land/std@0.90.0/fs/empty_dir.ts
Download https://deno.land/std@0.90.0/fs/ensure_file.ts
Download https://deno.land/std@0.90.0/async/mux_async_iterator.ts
Download https://deno.land/std@0.90.0/async/delay.ts
Download https://deno.land/std@0.90.0/async/pool.ts
Download https://deno.land/std@0.90.0/async/deferred.ts
Download https://deno.land/std@0.90.0/path/common.ts
Download https://deno.land/std@0.90.0/path/_interface.ts
Download https://deno.land/std@0.90.0/path/posix.ts
Download https://deno.land/std@0.90.0/path/win32.ts
Download https://deno.land/std@0.90.0/path/glob.ts
Download https://deno.land/std@0.90.0/_util/os.ts
Download https://deno.land/std@0.90.0/path/separator.ts
Download https://deno.land/std@0.90.0/testing/_diff.ts
Download https://deno.land/std@0.90.0/fmt/colors.ts
Download https://deno.land/std@0.90.0/node/_util/_util_callbackify.ts
Download https://deno.land/std@0.90.0/node/_util/_util_promisify.ts
Download https://deno.land/std@0.90.0/node/_util/_util_types.ts
Download https://deno.land/std@0.90.0/fs/_util.ts
Download https://deno.land/std@0.90.0/path/_util.ts
Download https://deno.land/std@0.90.0/path/_constants.ts
Check file:///example.ts
error: TS2439 [ERROR]: Import or export declaration in an ambient module declaration cannot reference module through relative module name.
    export * from '/v27/@types/node@14.14.35/https.d.ts';
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v27/@types/node@14.14.35/https.d.ts:2:5

TS2439 [ERROR]: Import or export declaration in an ambient module declaration cannot reference module through relative module name.
    import * as tls from '/v27/node:tls';
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v27/@types/node@14.14.35/https.d.ts:6:5

TS2439 [ERROR]: Import or export declaration in an ambient module declaration cannot reference module through relative module name.
    import * as http from '/v27/node:http';
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v27/@types/node@14.14.35/https.d.ts:7:5

TS2439 [ERROR]: Import or export declaration in an ambient module declaration cannot reference module through relative module name.
    import { URL } from '/v27/node:url';
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v27/@types/node@14.14.35/https.d.ts:8:5

TS2439 [ERROR]: Import or export declaration in an ambient module declaration cannot reference module through relative module name.
    export * from '/v27/@types/node@14.14.35/http.d.ts';
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v27/@types/node@14.14.35/http.d.ts:2:5

TS2439 [ERROR]: Import or export declaration in an ambient module declaration cannot reference module through relative module name.
    import * as stream from '/v27/node:stream';
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v27/@types/node@14.14.35/http.d.ts:6:5

TS2439 [ERROR]: Import or export declaration in an ambient module declaration cannot reference module through relative module name.
    import { URL } from '/v27/node:url';
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v27/@types/node@14.14.35/http.d.ts:7:5

TS2439 [ERROR]: Import or export declaration in an ambient module declaration cannot reference module through relative module name.
    import { Socket, Server as NetServer } from '/v27/node:net';
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v27/@types/node@14.14.35/http.d.ts:8:5

Found 8 errors.
```

**Comment by ije** [comment]
please use `https://esm.sh/html-minifier?no-check` instead, the `@types/node` is very complex to fix to deno, i have a plan to write standalone types for node builtin modules in the future. currently i just implemented the namespce declearation: https://github.com/postui/esm.sh/blob/master/types/node.ns.d.ts

**Comment by timreichen** [comment]
Thank you for your fast reply. That throws a different error concerning `require` though:
```sh
Download https://esm.sh/html-minifier?no-check
Download https://cdn.esm.sh/v27/html-minifier@4.0.0/deno/html-minifier.js?no-check
Download https://deno.land/std@0.90.0/node/fs.ts
Download https://cdn.esm.sh/v27/stream-http@3.1.1/deno/stream-http.js
Download https://cdn.esm.sh/v27/_node_buffer.js
Download https://cdn.esm.sh/v27/url@0.11.0/deno/url.js
Download https://cdn.esm.sh/v27/_node_process.js
Download https://cdn.esm.sh/v27/path-browserify@1.0.1/deno/path-browserify.js
Download https://cdn.esm.sh/v27/https-browserify@1.0.0/deno/https-browserify.js
Download https://cdn.esm.sh/v27/os-browserify@0.3.0/deno/browser.js
Download https://cdn.esm.sh/v27/querystring-es3@0.2.1/deno/querystring-es3.js
Download https://cdn.esm.sh/v27/punycode@2.1.1/deno/punycode.js
Download https://cdn.esm.sh/v27/buffer@6.0.3/deno/buffer.js
Download https://cdn.esm.sh/v27/util@0.12.3/deno/util.js
Download https://cdn.esm.sh/v27/events@3.3.0/deno/events.js
Download https://deno.land/std@0.90.0/node/_fs/promises/mod.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_constants.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_mkdir.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_lstat.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_stat.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_close.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_open.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_readFile.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_chown.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_readdir.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_realpath.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_access.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_copy.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_rename.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_readlink.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_mkdtemp.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_unlink.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_truncate.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_rmdir.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_appendFile.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_writeFile.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_watch.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_exists.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_chmod.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_common.ts
Download https://deno.land/std@0.90.0/node/_fs/promises/_fs_writeFile.ts
Download https://deno.land/std@0.90.0/node/_fs/promises/_fs_readFile.ts
Download https://deno.land/std@0.90.0/node/_utils.ts
Download https://deno.land/std@0.90.0/node/path.ts
Download https://deno.land/std@0.90.0/fs/mod.ts
Download https://deno.land/std@0.90.0/node/buffer.ts
Download https://deno.land/std@0.90.0/node/events.ts
Download https://deno.land/std@0.90.0/testing/asserts.ts
Download https://deno.land/std@0.90.0/async/mod.ts
Download https://deno.land/std@0.90.0/path/mod.ts
Download https://deno.land/std@0.90.0/fs/ensure_file.ts
Download https://deno.land/std@0.90.0/fs/exists.ts
Download https://deno.land/std@0.90.0/fs/empty_dir.ts
Download https://deno.land/std@0.90.0/fs/ensure_dir.ts
Download https://deno.land/std@0.90.0/fs/ensure_link.ts
Download https://deno.land/std@0.90.0/fs/ensure_symlink.ts
Download https://deno.land/std@0.90.0/fs/move.ts
Download https://deno.land/std@0.90.0/fs/copy.ts
Download https://deno.land/std@0.90.0/fs/expand_glob.ts
Download https://deno.land/std@0.90.0/fs/eol.ts
Download https://deno.land/std@0.90.0/fs/walk.ts
Download https://deno.land/std@0.90.0/testing/_diff.ts
Download https://deno.land/std@0.90.0/fmt/colors.ts
Download https://deno.land/std@0.90.0/_util/assert.ts
Download https://deno.land/std@0.90.0/_util/os.ts
Download https://deno.land/std@0.90.0/fs/_util.ts
Download https://deno.land/std@0.90.0/node/_errors.ts
Download https://deno.land/std@0.90.0/node/_fs/_fs_dirent.ts
Download https://deno.land/std@0.90.0/encoding/base64.ts
Download https://deno.land/std@0.90.0/encoding/hex.ts
Download https://deno.land/std@0.90.0/async/delay.ts
Download https://deno.land/std@0.90.0/async/mux_async_iterator.ts
Download https://deno.land/std@0.90.0/async/pool.ts
Download https://deno.land/std@0.90.0/async/deferred.ts
Download https://deno.land/std@0.90.0/path/_interface.ts
Download https://deno.land/std@0.90.0/path/glob.ts
Download https://deno.land/std@0.90.0/path/common.ts
Download https://deno.land/std@0.90.0/path/separator.ts
Download https://deno.land/std@0.90.0/path/win32.ts
Download https://deno.land/std@0.90.0/path/posix.ts
Download https://deno.land/std@0.90.0/node/util.ts
Download https://deno.land/std@0.90.0/path/_constants.ts
Download https://deno.land/std@0.90.0/path/_util.ts
Download https://deno.land/std@0.90.0/node/_util/_util_promisify.ts
Download https://deno.land/std@0.90.0/node/_util/_util_types.ts
Download https://deno.land/std@0.90.0/node/_util/_util_callbackify.ts
Check file:///example.ts
error: Uncaught ReferenceError: require is not defined
    at https://cdn.esm.sh/v27/html-minifier@4.0.0/deno/html-minifier.js?no-check:7:43918
    at https://cdn.esm.sh/v27/html-minifier@4.0.0/deno/html-minifier.js?no-check:1:875
    at https://cdn.esm.sh/v27/html-minifier@4.0.0/deno/html-minifier.js?no-check:12:296
    at https://cdn.esm.sh/v27/html-minifier@4.0.0/deno/html-minifier.js?no-check:1:875
    at https://cdn.esm.sh/v27/html-minifier@4.0.0/deno/html-minifier.js?no-check:16:204
```

**Comment by ije** [comment]
i just updated the server to handle the`require.resolve` in node module, but unfortunately it still can NOT work in deno since it needs to read some file in `node_modules` that is not exist after build.
