### ISSUE TITLE
Duplicate type declarations on some libraries

### ISSUE THREAD

**Issue by talentlessguy** [postui/esm.sh#36]
## Problem

While trying to import [xss](https://npm.im/xss):

```ts
import { filterXSS } from 'https://esm.sh/xss'
```

I came across with this error:

```sh
deno run -r render.ts
Download https://esm.sh/xss?nocheck
Download https://cdn.esm.sh/v28/xss@1.0.8/deno/xss.js
Download https://cdn.esm.sh/v28/xss@1.0.8/typings/xss.d.ts
Check file:///home/v1rtl/Coding/deno-libs/gql/graphiql/render.ts
error: TS2300 [ERROR]: Duplicate identifier 'OnTagHandler'.
      type OnTagHandler = (
           ~~~~~~~~~~~~
    at https://cdn.esm.sh/v28/xss@1.0.8/typings/xss.d.ts:93:12

    'OnTagHandler' was also declared here.
          type OnTagHandler = (
               ~~~~~~~~~~~~
        at https://cdn.esm.sh/v28/xss@1.0.8/typings/xss.d.ts:281:12

TS2300 [ERROR]: Duplicate identifier 'OnTagAttrHandler'.
      type OnTagAttrHandler = (
           ~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v28/xss@1.0.8/typings/xss.d.ts:99:12

    'OnTagAttrHandler' was also declared here.
          type OnTagAttrHandler = (
               ~~~~~~~~~~~~~~~~
        at https://cdn.esm.sh/v28/xss@1.0.8/typings/xss.d.ts:287:12

TS2300 [ERROR]: Duplicate identifier 'SafeAttrValueHandler'.
      type SafeAttrValueHandler = (
           ~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v28/xss@1.0.8/typings/xss.d.ts:106:12

    'SafeAttrValueHandler' was also declared here.
          type SafeAttrValueHandler = (
               ~~~~~~~~~~~~~~~~~~~~
        at https://cdn.esm.sh/v28/xss@1.0.8/typings/xss.d.ts:294:12

TS2300 [ERROR]: Duplicate identifier 'EscapeHandler'.
      type EscapeHandler = (str: string) => string;
           ~~~~~~~~~~~~~
    at https://cdn.esm.sh/v28/xss@1.0.8/typings/xss.d.ts:113:12

    'EscapeHandler' was also declared here.
          type EscapeHandler = (str: string) => string;
               ~~~~~~~~~~~~~
        at https://cdn.esm.sh/v28/xss@1.0.8/typings/xss.d.ts:301:12

TS2300 [ERROR]: Duplicate identifier 'OnTagHandler'.
      type OnTagHandler = (
           ~~~~~~~~~~~~
    at https://cdn.esm.sh/v28/xss@1.0.8/typings/xss.d.ts:281:12

    'OnTagHandler' was also declared here.
          type OnTagHandler = (
               ~~~~~~~~~~~~
        at https://cdn.esm.sh/v28/xss@1.0.8/typings/xss.d.ts:93:12

TS2300 [ERROR]: Duplicate identifier 'OnTagAttrHandler'.
      type OnTagAttrHandler = (
           ~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v28/xss@1.0.8/typings/xss.d.ts:287:12

    'OnTagAttrHandler' was also declared here.
          type OnTagAttrHandler = (
               ~~~~~~~~~~~~~~~~
        at https://cdn.esm.sh/v28/xss@1.0.8/typings/xss.d.ts:99:12

TS2300 [ERROR]: Duplicate identifier 'SafeAttrValueHandler'.
      type SafeAttrValueHandler = (
           ~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v28/xss@1.0.8/typings/xss.d.ts:294:12

    'SafeAttrValueHandler' was also declared here.
          type SafeAttrValueHandler = (
               ~~~~~~~~~~~~~~~~~~~~
        at https://cdn.esm.sh/v28/xss@1.0.8/typings/xss.d.ts:106:12

TS2300 [ERROR]: Duplicate identifier 'EscapeHandler'.
      type EscapeHandler = (str: string) => string;
           ~~~~~~~~~~~~~
    at https://cdn.esm.sh/v28/xss@1.0.8/typings/xss.d.ts:301:12

    'EscapeHandler' was also declared here.
          type EscapeHandler = (str: string) => string;
               ~~~~~~~~~~~~~
        at https://cdn.esm.sh/v28/xss@1.0.8/typings/xss.d.ts:113:12

Found 8 errors.
```

## Temporary solution

Add the `?no-check` to module URL.

**Comment by talentlessguy** [comment]
not an issue anymore in v47, closing
