### ISSUE TITLE
v45 transpiling problem with the latest aleph.js on feat-0.3-beta branch

### ISSUE THREAD

**Issue by guiguan** [postui/esm.sh#96]
Hi, after upgrading to v45, my app got this error in browser with both SSR and non-SSR:

```
Error: The requested module '../../prop-types@15.7.2/deno/prop-types.development.js' does not provide an export named 'any'
TypeError: The requested module '../../prop-types@15.7.2/deno/prop-types.development.js' does not provide an export named 'any'
    at async Aleph.importModule (file:///Users/[redacted]/aleph.js/server/aleph.ts:905:12)
    at async Renderer.renderPage (file:///Users/[redacted]/aleph.js/server/renderer.ts:99:42)
    at async Aleph.#renderPage (file:///Users/[redacted]/aleph.js/server/aleph.ts:620:24)
    at async file:///Users/[redacted]/aleph.js/server/aleph.ts:613:14
    at async Renderer.cache (file:///Users/[redacted]/aleph.js/server/renderer.ts:76:24)
    at async Aleph.renderPage (file:///Users/[redacted]/aleph.js/server/aleph.ts:612:20)
    at async Server.handle (file:///Users/[redacted]/aleph.js/server/server.ts:254:30)
    at async file:///Users/[redacted]/aleph.js/server/server.ts:329:15
```

The app is using the latest aleph.js on feat-0.3-beta branch, which was working just fine with v43. However, your alephjs.org works fine with v45. Any idea what could be the cause?

**Comment by ije** [comment]
@guiguan try to clean the cache in `deno info`

**Comment by guiguan** [comment]
@ije after removing the cache `deno info`, I got another error:

```
Uncaught Error: React Refresh runtime should not be included in the production bundle.
    at runtime.js:2
    at runtime.js:2
    at runtime.js:2
    at runtime.js:2
    at runtime.js:2
```

**Comment by guiguan** [comment]
I resolved the above [error](https://github.com/postui/esm.sh/issues/96#issuecomment-897514305), now I am still getting the first [error](https://github.com/postui/esm.sh/issues/96#issue-966625967) for v45 (latest master) even after cleaning all cahes. However, after reverting my `esm.sh` instance back to v43, everything works fine again.

**Comment by guiguan** [comment]
If I run `alephjs.org` locally against `aleph.js`, and both connect to v45, I got the same [error](https://github.com/postui/esm.sh/issues/96#issue-966625967)

**Comment by ije** [comment]
@guiguan thanks，I will look into it
